<?php

return [
    'brand' => [
        'name' => 'Learning-Cube Coaching-Classes for STD 6th to 12th',
        'tagline' => 'Strong Foundations. Confident Results.',
        'descriptor' => 'India’s trusted tutoring & coaching hub for Classes 6–12 across all major school boards.',
    ],
    'navigation' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Programs', 'route' => 'programs'],
        ['label' => 'Results & Testimonials', 'route' => 'results'],
        ['label' => 'Resources', 'route' => 'resources'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'cta' => [
        ['label' => 'Book a Free Demo Class', 'href' => '#contact'],
        ['label' => 'Talk to an Academic Counsellor', 'href' => '#contact'],
    ],
    'programs' => [
        [
            'name' => 'Junior Foundation Program',
            'grades' => 'Classes 6th to 8th',
            'focus' => 'A concept-building program that strengthens fundamentals in core subjects while developing curiosity, study discipline, and analytical skills. Ideal for students seeking strong academic foundations and early preparation through structured Classes 6-8 coaching.',
            'boards' => 'CBSE, ICSE, State Boards',
            'mode' => 'Online + Classroom',
            'frequency' => '3–4 classes / week',
            'who' => 'Students who need concept building, homework guidance, and Olympiad introduction.',
            'mode_detail' => 'Online / Offline / Hybrid with recorded sessions.',
            'duration' => 'Annual plan | 3–4 classes per week',
        ],
        [
            'name' => 'High School Board Prep',
            'grades' => 'Classes 9th to 10th',
            'focus' => 'A structured board-preparation program offering NCERT clarity, chapter-wise testing, and targeted revision to help Classes 9-10 students improve accuracy, confidence, and overall board exam performance through systematic coaching and continuous assessment.',
            'boards' => 'CBSE, ICSE, State Boards',
            'mode' => 'Hybrid batches',
            'frequency' => '4–5 classes / week',
            'who' => 'Learners targeting high board scores with rigorous practice.',
            'mode_detail' => 'Online classes + weekend centre doubt clinics.',
            'duration' => '10–12 month coverage + pre-board bootcamps',
        ],
        [
            'name' => 'Senior Excellence Program',
            'grades' => 'Classes 11th to 12th',
            'focus' => 'Stream-focused coaching for Classes 11-12, offering deep subject understanding, board exam readiness, and foundational support for competitive exams. Ideal for Science and Commerce students seeking structured senior secondary coaching and consistent academic improvement.',
            'boards' => 'CBSE, ISC, State Boards, JEE, NEET, CUET',
            'mode' => 'Online + Partner Centres',
            'frequency' => '5 classes / week',
            'who' => 'Science, Commerce, and Humanities students needing depth + exam skills.',
            'mode_detail' => 'Live & lab support with problem-solving pods.',
            'duration' => '2-year & crash tracks | 4–5 classes per week',
        ],
        [
            'name' => 'Crash Course & Holiday Batches',
            'grades' => 'Short-Term',
            'focus' => 'Fast-track revision batches are designed to boost exam readiness through intensive practice, mock tests, and discussions of essential questions. Ideal for students preparing for pre-boards, finals, and quick concept revision during holiday or short-term study periods.',
            'boards' => 'All Boards',
            'mode' => 'Fast-track online/live',
            'frequency' => 'Custom schedules',
            'who' => 'Students seeking short-term improvement in specific subjects or exams.',
            'mode_detail' => 'Power-packed online/live sprint batches.',
            'duration' => '4–12 week intensives + revision marathons',
        ],
    ],
    'specialised_support' => [
        'Homework & Assignment Support',
        'Doubt-Solving Sessions',
        'Remedial Classes',
        'Holiday Crash Courses',
    ],
    'strengths' => [
        'intro' => 'A results-driven coaching environment combining expert guidance, data-based evaluation, and smart learning resources to help students improve understanding, boost scores, and grow confidently.',
        'items' => [
            [
                'title' => 'Highly Experienced Teachers',
                'body' => 'Our faculty comprises accomplished educators with rich teaching expertise, deep subject mastery, and a passion for mentoring—delivering impactful learning that builds confidence, clarity, and academic excellence.',
                'variant' => 'dark',
                'icon' => 'ri-user-star-line',
            ],
            [
                'title' => 'Regular Chapter-Wise Tests',
                'body' => 'Consistent evaluation drives improvement. We conduct chapter-wise assessments after every topic to reinforce understanding, measure progress, and address learning gaps through precise, data-driven feedback.',
                'variant' => 'light',
                'icon' => 'ri-file-list-3-line',
            ],
            [
                'title' => 'Limited Students Per Batch',
                'body' => 'We prioritize quality over quantity. Small, well-structured batches ensure personalized attention, better engagement, and effective concept clarity—creating a student-centric environment that nurtures growth and focus.',
                'variant' => 'dark',
                'icon' => 'ri-group-2-line',
            ],
            [
                'title' => 'Innovative Teaching Methods',
                'body' => 'We use interactive tools, visual aids, and adaptive techniques to make complex concepts easy to grasp and retain, fostering a dynamic classroom where every student can thrive.',
                'variant' => 'light',
                'icon' => 'ri-lightbulb-line',
            ],
            [
                'title' => 'Performance Analysis via Detailed Reports',
                'body' => "Each student's progress is meticulously tracked through detailed performance analytics, empowering parents and learners with valuable insights to enhance preparation and sustain continuous improvement.",
                'variant' => 'dark',
                'icon' => 'ri-bar-chart-box-line',
            ],
            [
                'title' => 'One-on-One Counselling & Personalized Attention',
                'body' => 'We believe every learner is unique. Our one-on-one counselling ensures tailored academic guidance, emotional support, and strategic mentorship—helping students achieve their full potential with confidence.',
                'variant' => 'accent',
                'icon' => 'ri-user-heart-line',
            ],
            [
                'title' => 'Transport Facility Available',
                'body' => 'We provide a well-managed and reliable transport service to ensure students travel safely and comfortably every day. With planned routes, on-time operations, and a child-friendly environment, parents can rely on a smooth, secure commute for their children.',
                'variant' => 'light_slate',
                'icon' => 'ri-bus-line',
                'icon_bg' => 'orange',
            ],
            [
                'title' => 'Official Learning-Cube Mobile App',
                'body' => 'Our dedicated mobile app keeps learning organized and communication effortless. Parents and students can easily access:',
                'bullets' => [
                    'Homework and class updates',
                    'Test schedules and results',
                    'Digital notes and study materials',
                    'Attendance records',
                    'Important alerts and announcements',
                ],
                'body_end' => 'A seamless digital experience that keeps academics transparent, structured, and accessible anytime, anywhere.',
                'variant' => 'light_slate',
                'icon' => 'ri-smartphone-line',
                'icon_bg' => 'mint',
            ],
        ],
    ],
    'subjects' => [
        'boards' => ['CBSE', 'ICSE', 'State Boards', 'IB', 'Cambridge (IGCSE & A-Levels)'],
        'middle_school' => ['Mathematics', 'Science', 'English', 'Social Science', 'Hindi', 'Regional Languages'],
        'senior_science' => ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'Computer Science'],
        'senior_commerce' => ['Accountancy', 'Business Studies', 'Economics', 'Mathematics'],
        'senior_humanities' => ['Economics', 'Political Science', 'History', 'Geography', 'Sociology', 'Psychology'],
    ],
    'support_steps' => [
        'intro' => 'We believe that every student deserves a personalized, transparent, and empowering learning experience. Our step-by-step support system ensures clarity, consistency, and continuous progress throughout the academic year.',
        'steps' => [
            [
                'title' => 'Free Academic Counselling',
                'body' => "We start by understanding the student's strengths, learning style, and academic goals, helping us guide them in the right direction from the very beginning.",
                'banner' => 'yellow',
                'icon' => 'ri-user-search-line',
                'icon_image' => 'images/homepage/icon_1.png',
            ],
            [
                'title' => 'Customized Study Plan',
                'body' => 'A customized plan is created for each student—covering subjects, schedules, and learning strategies—to ensure steady improvement and stress-free progress.',
                'banner' => 'lime',
                'icon' => 'ri-book-2-line',
                'icon_image' => 'images/homepage/icon_2.png',
            ],
            [
                'title' => 'Engaging Classes & Doubt Support',
                'body' => 'Interactive teaching, concept-based learning, and dedicated doubt-solving sessions help students understand deeply, think clearly, and stay confident in every subject.',
                'banner' => 'teal',
                'icon' => 'ri-team-line',
                'icon_image' => 'images/homepage/icon_3.png',
            ],
            [
                'title' => 'Regular Tests & Analysis',
                'body' => 'We conduct consistent topic-wise tests and share easy-to-understand performance reports. Parents and students receive clear insights on strengths, areas of improvement, and the exact steps needed to enhance scores.',
                'banner' => 'blue',
                'icon' => 'ri-file-chart-line',
                'icon_image' => 'images/homepage/icon_4.png',
            ],
            [
                'title' => 'Continuous Parent Communication',
                'body' => "Parents stay updated through monthly reviews, progress discussions, and direct access to teachers/coordinators—ensuring complete clarity, trust, and involvement throughout the student's learning journey.",
                'banner' => 'blue_dark',
                'icon' => 'ri-customer-service-2-line',
                'icon_image' => 'images/homepage/icon_5.png',
            ],
        ],
    ],
    'results' => [
        'stats' => [
            ['label' => 'Improved marks within one term', 'value' => '90% students'],
            ['label' => 'Students guided across boards', 'value' => '1000+ learners'],
            ['label' => 'Top performer core subject scores', 'value' => 'Consistent 90%+'],
        ],
        'google_reviews_url' => 'https://www.google.com/search?q=learning-cube+coaching+reviews',
        'testimonials' => [
            [
                'quote' => 'Learning-Cube helped my son move from 60s to 90s in Maths within a year. The teachers are patient and very supportive.',
                'author' => 'Parent of Class 9 CBSE Student',
                'time' => '2 months ago',
                'stars' => 5,
            ],
            [
                'quote' => 'The regular tests and feedback kept me on track for my Class 10 boards. I felt confident during exams.',
                'author' => 'Class 10 ICSE Student',
                'time' => '1 month ago',
                'stars' => 5,
            ],
            [
                'quote' => 'Hybrid learning and recorded sessions meant I never missed a concept even during travel.',
                'author' => 'Class 11 IGCSE Student',
                'time' => '3 weeks ago',
                'stars' => 5,
            ],
        ],
        'stories' => [
            ['title' => 'From 65% to 88% in Class 9 Maths (CBSE)', 'body' => 'Focused doubt resolution, Saturday test series, and revision bootcamps boosted conceptual clarity and exam stamina.'],
            ['title' => 'ICSE Class 10 – Science from 70 to 92', 'body' => 'Targeted lab manual practice, weekly practical orals, and rapid-fire quizzes improved accuracy.'],
            ['title' => 'Holiday Crash Course for Class 12 Commerce', 'body' => '90-day intensive revision with problem marathons and evaluation rubrics delivered an aggregate of 93%.'],
        ],
    ],
    'resources' => [
        ['title' => 'How to Choose the Right Stream after Class 10', 'description' => 'A friendly guide to align strengths with Science, Commerce, or Humanities pathways.'],
        ['title' => 'How to Prepare for Board Exams without Stress', 'description' => 'Simple rituals plus productivity frameworks to avoid burnout.'],
        ['title' => 'Study Timetable Templates for Classes 6–12', 'description' => 'Ready-to-use weekly layouts to balance school, coaching, and hobbies.'],
    ],
    'contact' => [
        'headline' => 'Get in Touch with Learning-Cube',
        'subtext' => 'Have questions about batches, fees, or programs? Share a few details – our counsellor will call you within 24 working hours.',
        'phone' => ['+91 98980 75217', '+91 70160 46616'],
        'email' => 'support@learning-cube.com',
        'hours' => '10:00 AM – 8:00 PM (IST), Monday to Sunday',
        'address' => '217, Exult Shoppers, Nr. Sidhhiviniyak Temple, Vesu Main Road, Vesu, Surat, Gujarat-395007',
        'social' => [
            ['label' => 'Instagram', 'href' => '#', 'icon' => 'ri-instagram-line'],
            ['label' => 'Facebook', 'href' => '#', 'icon' => 'ri-facebook-circle-line'],
            ['label' => 'YouTube', 'href' => '#', 'icon' => 'ri-youtube-line'],
            ['label' => 'LinkedIn', 'href' => '#', 'icon' => 'ri-linkedin-line'],
        ],
    ],
    'footer' => [
        'title' => 'Learning-Cube Coaching Classes For STD 6th to 12th',
        'description' => 'Focused academic programs for Classes 6-12 designed to strengthen concepts, improve performance, and build long-term success through structured teaching, personalised attention, and consistent evaluation.',
        'image' => 'images/footer_image.png',
        'image_webp' => 'images/footer_image.webp',
        'company' => [
            ['label' => 'About', 'route' => 'about'],
            ['label' => 'Program', 'route' => 'programs'],
            ['label' => 'Service', 'href' => '#'],
        ],
        'student_parent' => [
            ['label' => 'Demo Classes', 'href' => '#contact'],
            ['label' => 'Blog', 'href' => '#'],
            ['label' => 'FAQs', 'href' => '#'],
            ['label' => 'Gallery', 'href' => '#'],
        ],
        'follow_us_label' => 'Follow us',
        'address_lines' => [
            '217, Exult Shoppers, Nr.',
            'Siddhi Vinayak Temple, Vesu',
            'Main Road, Vesu, Surat,',
            'Gujarat-395007',
        ],
        'policies' => [
            ['label' => 'Privacy Policy', 'href' => '#'],
            ['label' => 'Terms of Service', 'href' => '#'],
            ['label' => 'Sitemap', 'href' => '#'],
        ],
        'copyright' => '© 2025 Learning-Cube Coaching Classes. All Rights Reserved.',
    ],
];

